server:
  port: 8003
spring:
  main:
    web-application-type: reactive
  application:
    name: short-link-gateway
  data:
    redis:
      host: 192.168.100.128
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.128:8848
    gateway:
      routes:
        - id: short-link-admin
          uri: lb://short-link-admin/api/short-link/admin/**
          predicates:
            - Path=/api/short-link/admin/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/short-link/admin/v1/user/login
                  - /api/short-link/admin/v1/user/has-username

        - id: short-link-project
          uri: lb://short-link-project/api/short-link/**
          predicates:
            - Path=/api/short-link/**
          filters:
            - name: TokenValidate